"""Schooln migration.

Revision ID: 2d73e251fc0f
Revises: d3187a350268
Create Date: 2023-07-10 02:06:18.064087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d73e251fc0f'
down_revision = 'd3187a350268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.String(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
