"""linkage table adjust

Revision ID: 3d174c4fe94f
Revises: ab3d0d80e4f6
Create Date: 2023-06-08 00:35:48.172548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d174c4fe94f'
down_revision = 'ab3d0d80e4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linkage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linkage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('active')

    # ### end Alembic commands ###
