"""models upgrade2

Revision ID: 44aaaa08979a
Revises: 3c6beb484e50
Create Date: 2023-07-04 01:25:33.835548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44aaaa08979a'
down_revision = '3c6beb484e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitation', schema=None) as batch_op:
        batch_op.drop_column('approval')

    # ### end Alembic commands ###
