"""test migration.

Revision ID: 4e0b941bb7d5
Revises: bb4dc3da39fd
Create Date: 2023-07-01 15:23:52.481061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0b941bb7d5'
down_revision = 'bb4dc3da39fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_column('release_date')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
