"""solicitation model.

Revision ID: 5583c4f50c36
Revises: 3d174c4fe94f
Create Date: 2023-06-14 23:41:46.049538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5583c4f50c36'
down_revision = '3d174c4fe94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('rating', sa.String(length=6), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('linkage', schema=None) as batch_op:
        batch_op.drop_column('presence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linkage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presence', sa.BOOLEAN(), nullable=False))

    op.drop_table('solicitation')
    # ### end Alembic commands ###
