"""column 'name' in table user added.

Revision ID: ab3d0d80e4f6
Revises: 145252a7f891
Create Date: 2023-06-02 00:15:30.738169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3d0d80e4f6'
down_revision = '145252a7f891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_column('discipline')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discipline', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
